#ifndef __SPIDEFS_H__
#define __SPIDEFS_H__

#include <stdint.h>

#define SOT ((uint8_t)0x02)
#define EOT ((uint8_t)0x03)


// The SPI command structure.
struct spi_pkt
{
    uint8_t start_of_line;
    uint8_t len;
    uint8_t cmd;
    uint8_t end_of_line;
    uint8_t checksum;
};


union spi_pkt2
{
    uint8_t mRaw[255];
    struct
    {
        uint8_t mStartOfLine;
        uint8_t mLen;
        uint8_t mTagIx;
        uint8_t mData[252];
    } mField;
};

enum spi_cmd
{
    SPI_CMD_INIT_DEV_INFO = 0,
    SPI_CMD_INIT_CFG,
    SPI_CMD_INIT_NETWORK,
    SPI_CMD_UPDATE_STATS,
    SPI_CMD_UPDATE_TIME,
    SPI_CMD_UPDATE_DATE,
    SPI_CMD_WR_FEED_NOW,
    SPI_CMD_WR_FEED_TIME,
    SPI_CMD_WR_FEED_CALENDAR,
    SPI_CMD_INIT_NET_INFO,
    SPI_CMD_UPDATE_NET_CFG,
    SPI_CMD_INIT_STATS
};


enum spi_tag_ix {
    SPI_TAG_IX_ZERO = 0,
    SPI_TAG_IX_EMPTY,

    // Info.
    SPI_TAG_IX_INFO_FIRST,
    SPI_TAG_IX_INFO_FW_VERSION = SPI_TAG_IX_INFO_FIRST,
    SPI_TAG_IX_INFO_BUILD_DATE,
    SPI_TAG_IX_INFO_BUILD_TIME,
    SPI_TAG_IX_INFO_GIT_HASH,
    SPI_TAG_IX_INFO_DB_STATUS,
    SPI_TAG_IX_INFO_RTCC_TEMP,
    SPI_TAG_IX_INFO_LAST = SPI_TAG_IX_INFO_RTCC_TEMP,

    // Global: Time and Date.
    SPI_TAG_IX_CFG_GLOBAL_DATE,
    SPI_TAG_IX_CFG_GLOBAL_TIME,

    // Configuration.
    SPI_TAG_IX_CFG_FIRST,
    SPI_TAG_IX_CFG_PAD_ENABLE = SPI_TAG_IX_CFG_FIRST,
    SPI_TAG_IX_CFG_PAD_DISABLE,
    SPI_TAG_IX_CFG_LAST = SPI_TAG_IX_CFG_PAD_DISABLE,

    SPI_TAG_IX_CFG_FEED_TIME,

    // Calendar.
    SPI_TAG_IX_CFG_CALENDAR_FIRST,
    SPI_TAG_IX_CFG_CALENDAR_06_00 = SPI_TAG_IX_CFG_CALENDAR_FIRST,
    SPI_TAG_IX_CFG_CALENDAR_07_00,
    SPI_TAG_IX_CFG_CALENDAR_08_00,
    SPI_TAG_IX_CFG_CALENDAR_09_00,
    SPI_TAG_IX_CFG_CALENDAR_10_00,
    SPI_TAG_IX_CFG_CALENDAR_11_00,
    SPI_TAG_IX_CFG_CALENDAR_12_00,
    SPI_TAG_IX_CFG_CALENDAR_13_00,
    SPI_TAG_IX_CFG_CALENDAR_14_00,
    SPI_TAG_IX_CFG_CALENDAR_15_00,
    SPI_TAG_IX_CFG_CALENDAR_16_00,
    SPI_TAG_IX_CFG_CALENDAR_17_00,
    SPI_TAG_IX_CFG_CALENDAR_18_00,
    SPI_TAG_IX_CFG_CALENDAR_19_00,
    SPI_TAG_IX_CFG_CALENDAR_20_00,
    SPI_TAG_IX_CFG_CALENDAR_21_00,
    SPI_TAG_IX_CFG_CALENDAR_LAST = SPI_TAG_IX_CFG_CALENDAR_21_00,

    // Network configuration.
    SPI_TAG_IX_NET_MAC_ADDR,
    SPI_TAG_IX_NET_IPV4_ADD,
    SPI_TAG_IX_NET_SUBNET_MASK,
    SPI_TAG_IX_NET_GW_ADD,

    SPI_TAG_IX_NET_USE_DHCP,
    SPI_TAG_IX_NET_USE_MANUAL,
    SPI_TAG_IX_NET_STATIC_FIRST,
    SPI_TAG_IX_NET_STATIC_IPV4_ADD_0 = SPI_TAG_IX_NET_STATIC_FIRST,
    SPI_TAG_IX_NET_STATIC_IPV4_ADD_1,
    SPI_TAG_IX_NET_STATIC_IPV4_ADD_2,
    SPI_TAG_IX_NET_STATIC_IPV4_ADD_3,
    SPI_TAG_IX_NET_STATIC_SUBNET_MASK_0,
    SPI_TAG_IX_NET_STATIC_SUBNET_MASK_1,
    SPI_TAG_IX_NET_STATIC_SUBNET_MASK_2,
    SPI_TAG_IX_NET_STATIC_SUBNET_MASK_3,
    SPI_TAG_IX_NET_STATIC_GW_ADD_0,
    SPI_TAG_IX_NET_STATIC_GW_ADD_1,
    SPI_TAG_IX_NET_STATIC_GW_ADD_2,
    SPI_TAG_IX_NET_STATIC_GW_ADD_3,
    SPI_TAG_IX_NET_STATIC_LAST = SPI_TAG_IX_NET_STATIC_GW_ADD_3,

    // Network statistics.
    SPI_TAG_IX_STATS_FIRST,
    SPI_TAG_IX_STATS_TX = SPI_TAG_IX_STATS_FIRST,
    SPI_TAG_IX_STATS_RX,
    SPI_TAG_IX_STATS_FW,
    SPI_TAG_IX_STATS_DROP,
    SPI_TAG_IX_STATS_CHK_ERR,
    SPI_TAG_IX_STATS_LEN_ERR,
    SPI_TAG_IX_STATS_MEM_ERR,
    SPI_TAG_IX_STATS_RT_ERR,
    SPI_TAG_IX_STATS_PRO_ERR,
    SPI_TAG_IX_STATS_OPT_ERR,
    SPI_TAG_IX_STATS_ERR,
    SPI_TAG_IX_STATS_LAST = SPI_TAG_IX_STATS_ERR,

    // Network interface.
    SPI_TAG_IX_LAST = SPI_TAG_IX_STATS_ERR,
    SPI_TAG_IX_STATS_QTY
};

#endif // __SPIDEFS_H__
